gpShortcodeMeta={
	attributes:[
		{
			label:"Icon",
			id:"type",
		//	help: "ie camera-retro.",
			controlType:"select-control", 
			selectLabelValues:[{'Bar chart':'bar-chart'},
			                   {'Beaker':'beaker'},
			                   {'Book':'book'},
			                   {'Briefcase':'briefcase'},
			                   {'Camera-retro':'camera-retro'},
			                   {'Camera':'camera'},
			                   {'Check':'check'},
			                   {'Cog':'cog'},
			                   {'Delicious':'delicious'},
			                   {'Desktop':'desktop'},				                   
			                   {'Download':'download'},
			                   {'Edit':'edit'},
			                   {'Envelope':'envelope'},
			                   {'Eye open':'eye-open'},
			                   {'Facebook':'facebook'},
			                   {'Fighter jet':'fighter-jet'},
			                   {'File':'file'},
			                   {'Film':'film'},
			                   {'Flickr':'flickr'},
			                   {'Folder open':'folder-open'},
			                   {'Folder close':'folder-close'},
			                   {'Github':'github'},
			                   {'Google plus':'google-plus'},
			                   {'Hand down':'hand-dwon'},
			                   {'Hand up':'hand-up'},
			                   {'Heart-empty':'heart-empty'},
			                   {'Home':'home'},
			                   {'Key':'key'},
			                   {'Laptop':'laptop'},
			                   {'Link':'link'},
			                   {'Linkedin':'linkedin'},
			                   {'Leaf':'leaf'},
			                   {'Magic':'magic'},
			                   {'Medkit':'medkit'},
			                   {'Mobile phone':'mobile-phone'},
			                   {'Music':'music'},
			                   {'Ok':'ok'},
			                   {'Pencil':'pencil'},
			                   {'Phone':'phone'},
			                   {'Picture':'picture'},
			                   {'Pinterest':'pinterest'},
			                   {'Play circel':'play-circel'},
			                   {'Plus':'plus'},
			                   {'Plus sign':'plus-sign'},
			                   {'Print':'print'},
			                   {'Search':'search'},
			                   {'Shopping cart':'shopping-cart'},
			                   {'Sitemap':'sitemap'},
			                   {'Star empty':'star-empty'},
			                   {'Truck':'truck'},
			                   {'Twitter':'twitter'},
			                   {'User':'user'},
			                   {'Wrench':'wrench'},
			                   {'Youtube':'youtube'},
			                   ]
		},
		{
			label:"Size",
			id:"size",
			help:"E.g. 20px or 2em. Leave empty for default",
		},
		{
			label:"Color",
			id:"color",
			help:"Pick color or leave empty for default.",
			controlType:"colourpicker-control"
		}
		],
		shortcode:"icon"
};